"""Local LLM Runtime Foundation public API."""

from .contracts import (
    CONTRACT_VERSION,
    GENERATION_REQUEST_VERSION,
    GENERATION_RESULT_VERSION,
    RUNTIME_OPTIONS_VERSION,
    AccelerationSettings,
    ContextSettings,
    EngineCapability,
    EngineIdentity,
    ExecutionTrace,
    GenerationRequest,
    GenerationResult,
    HealthResult,
    KVCacheSettings,
    LifecycleState,
    LoadResult,
    ModelArtifactBinding,
    PrefillSettings,
    PromptCacheSettings,
    RuntimeErrorRecord,
    RuntimeMetrics,
    RuntimeOptions,
    RuntimeSettingsResolution,
    StreamEvent,
    TokenUsage,
    UnloadResult,
)
from .core import InferenceManager, RuntimeCore
from .client import LocalRuntimeClient, RemoteRuntimeError
from .host import HostProfile
from .version import FOUNDATION_VERSION

__all__ = [
    "FOUNDATION_VERSION",
    "CONTRACT_VERSION",
    "RUNTIME_OPTIONS_VERSION",
    "GENERATION_REQUEST_VERSION",
    "GENERATION_RESULT_VERSION",
    "AccelerationSettings",
    "ContextSettings",
    "EngineCapability",
    "EngineIdentity",
    "ExecutionTrace",
    "GenerationRequest",
    "GenerationResult",
    "HealthResult",
    "KVCacheSettings",
    "LifecycleState",
    "LoadResult",
    "ModelArtifactBinding",
    "PrefillSettings",
    "PromptCacheSettings",
    "RuntimeErrorRecord",
    "RuntimeMetrics",
    "RuntimeOptions",
    "RuntimeSettingsResolution",
    "StreamEvent",
    "TokenUsage",
    "UnloadResult",
    "HostProfile",
    "RuntimeCore",
    "InferenceManager",
    "LocalRuntimeClient",
    "RemoteRuntimeError",
]
